<|"nh" -> 3, "Nd" -> 0, "Dimension" -> 3, 
 "RawBasis" -> {h[-a, c]*h[a, b]*h[-b, -c], h[a, -a]*h[-b, -c]*h[b, c], 
   h[a, -a]*h[b, -b]*h[c, -c]}, "RawCount" -> 3, 
 "IBPSolution" -> {{c1 -> 0, c2 -> 0, c3 -> 0}}, "IBPFreeParameters" -> {}, 
 "IBPRelationMatrix" -> {}, "IBPRelationExpressions" -> {}, 
 "IBPPivots" -> {}, "IBPBasis" -> {h[-a, c]*h[a, b]*h[-b, -c], 
   h[a, -a]*h[-b, -c]*h[b, c], h[a, -a]*h[b, -b]*h[c, -c]}, "IBPCount" -> 3, 
 "RedefDeltaBasis" -> {}, "RedefShiftImages" -> {}, 
 "RedefProjectedData" -> {}, "RedefImageVectors" -> {}, 
 "RedefIndependentRows" -> {}, "RedefIndependentVectors" -> {}, 
 "RedefIndependentDeltas" -> {}, "RedefRank" -> 0, "RedefPivots" -> {}, 
 "RedefinitionRules" -> {}, "PhysicalBasis" -> {h[-a, c]*h[a, b]*h[-b, -c], 
   h[a, -a]*h[-b, -c]*h[b, c], h[a, -a]*h[b, -b]*h[c, -c]}, 
 "PhysicalCount" -> 3|>
