<|"nh" -> 2, "Nd" -> 2, "Dimension" -> 4, 
 "RawBasis" -> {h[a, b]*PD[-b][PD[-a][h[c, -c]]], 
   h[a, b]*PD[-c][PD[-b][h[-a, c]]], h[a, -a]*PD[-c][PD[-b][h[b, c]]], 
   h[a, b]*PD[-c][PD[c][h[-a, -b]]], h[a, -a]*PD[-c][PD[c][h[b, -b]]], 
   PD[-b][h[c, -c]]*PD[b][h[a, -a]], PD[-a][h[a, b]]*PD[-c][h[-b, c]], 
   PD[b][h[a, -a]]*PD[-c][h[-b, c]], PD[-b][h[-a, -c]]*PD[c][h[a, b]], 
   PD[-c][h[-a, -b]]*PD[c][h[a, b]]}, "RawCount" -> 10, 
 "IBPSolution" -> {{c6 -> c5, c8 -> c1 + c3, c9 -> c2 - c7, c10 -> c4}}, 
 "IBPFreeParameters" -> {c1, c2, c3, c4, c5, c7}, 
 "IBPRelationMatrix" -> {{1, 0, 0, 0, 0, 0, 0, 1, 0, 0}, 
   {0, 1, 0, 0, 0, 0, 0, 0, 1, 0}, {0, 0, 1, 0, 0, 0, 0, 1, 0, 0}, 
   {0, 0, 0, 1, 0, 0, 0, 0, 0, 1}, {0, 0, 0, 0, 1, 1, 0, 0, 0, 0}, 
   {0, 0, 0, 0, 0, 0, 1, 0, -1, 0}}, "IBPRelationExpressions" -> 
  {h[a, b]*PD[-b][PD[-a][h[c, -c]]] + PD[b][h[a, -a]]*PD[-c][h[-b, c]], 
   h[a, b]*PD[-c][PD[-b][h[-a, c]]] + PD[-b][h[-a, -c]]*PD[c][h[a, b]], 
   PD[b][h[a, -a]]*PD[-c][h[-b, c]] + h[a, -a]*PD[-c][PD[-b][h[b, c]]], 
   h[a, b]*PD[-c][PD[c][h[-a, -b]]] + PD[-c][h[-a, -b]]*PD[c][h[a, b]], 
   PD[-b][h[c, -c]]*PD[b][h[a, -a]] + h[a, -a]*PD[-c][PD[c][h[b, -b]]], 
   PD[-a][h[a, b]]*PD[-c][h[-b, c]] - PD[-b][h[-a, -c]]*PD[c][h[a, b]]}, 
 "IBPPivots" -> {1, 2, 3, 4, 5, 7}, 
 "IBPBasis" -> {PD[-b][h[c, -c]]*PD[b][h[a, -a]], 
   PD[b][h[a, -a]]*PD[-c][h[-b, c]], PD[-b][h[-a, -c]]*PD[c][h[a, b]], 
   PD[-c][h[-a, -b]]*PD[c][h[a, b]]}, "IBPCount" -> 4, 
 "RedefDeltaBasis" -> {}, "RedefShiftImages" -> {}, 
 "RedefProjectedData" -> {}, "RedefImageVectors" -> {}, 
 "RedefIndependentRows" -> {}, "RedefIndependentVectors" -> {}, 
 "RedefIndependentDeltas" -> {}, "RedefRank" -> 0, "RedefPivots" -> {}, 
 "RedefinitionRules" -> {}, "PhysicalBasis" -> 
  {PD[-b][h[c, -c]]*PD[b][h[a, -a]], PD[b][h[a, -a]]*PD[-c][h[-b, c]], 
   PD[-b][h[-a, -c]]*PD[c][h[a, b]], PD[-c][h[-a, -b]]*PD[c][h[a, b]]}, 
 "PhysicalCount" -> 4|>
